title: eyeBox - DPP Documentation
description: Project documentation for eyeBox
theme: just-the-docs

url: https://splendiferousnoctifer.github.io/eyeBox

aux_links:
  Repository: https://github.com/splendiferousnoctifer/eyeBox

